/** Tailwind config — ported verbatim from the OMR GradePro design system. */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  theme: {
    extend: {
      colors: {
        "on-primary-container": "#86a0cd",
        secondary: "#505f76",
        "tertiary-fixed": "#89f5e7",
        "on-background": "#191c1e",
        "secondary-fixed-dim": "#b7c8e1",
        "on-surface-variant": "#43474e",
        "surface-dim": "#d8dadc",
        "on-tertiary-fixed-variant": "#005049",
        "on-secondary": "#ffffff",
        "inverse-on-surface": "#eff1f3",
        "surface-bright": "#f7f9fb",
        "on-primary-fixed": "#001b3c",
        "outline-variant": "#c4c6cf",
        "on-error": "#ffffff",
        surface: "#f7f9fb",
        "surface-container": "#eceef0",
        "on-primary-fixed-variant": "#2d476f",
        "primary-fixed-dim": "#adc7f7",
        "on-error-container": "#93000a",
        outline: "#74777f",
        "primary-fixed": "#d6e3ff",
        "error-container": "#ffdad6",
        "on-tertiary": "#ffffff",
        "surface-container-highest": "#e0e3e5",
        "surface-container-low": "#f2f4f6",
        "inverse-primary": "#adc7f7",
        "tertiary-container": "#003d37",
        background: "#f7f9fb",
        "surface-variant": "#e0e3e5",
        "inverse-surface": "#2d3133",
        "on-tertiary-fixed": "#00201d",
        "secondary-container": "#d0e1fb",
        "on-secondary-fixed": "#0b1c30",
        "tertiary-fixed-dim": "#6bd8cb",
        "surface-container-high": "#e6e8ea",
        "on-tertiary-container": "#3cafa2",
        "on-secondary-container": "#54647a",
        "on-surface": "#191c1e",
        error: "#ba1a1a",
        tertiary: "#002522",
        "on-secondary-fixed-variant": "#38485d",
        primary: "#002045",
        "surface-container-lowest": "#ffffff",
        "primary-container": "#1a365d",
        "on-primary": "#ffffff",
        "surface-tint": "#455f88",
        "secondary-fixed": "#d3e4fe",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        md: "16px",
        "container-max": "1280px",
        lg: "24px",
        sm: "8px",
        gutter: "20px",
        base: "4px",
        xs: "4px",
        xl: "32px",
      },
      maxWidth: {
        "container-max": "1280px",
      },
      fontFamily: {
        "headline-md": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "headline-sm": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "data-mono": ["JetBrains Mono", "monospace"],
      },
      fontSize: {
        "headline-md": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-sm": ["12px", { lineHeight: "16px", fontWeight: "400" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-sm": ["18px", { lineHeight: "24px", fontWeight: "600" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "data-mono": ["13px", { lineHeight: "18px", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
};
